#!/usr/bin/env python3
# -*- coding: utf-8 -*-

"""
select_lead_snps.py
===================

Select representative lead SNPs from GWAS results using
PLINK LD clumping results.

Workflow
--------
GWAS summary statistics
        |
        v
PLINK LD clumping
        |
        v
LD groups / clumps
        |
        v
Select SNP with the smallest GWAS P-value
within each LD group
        |
        v
Representative lead SNPs

Input
-----
1. GWAS summary statistics
   Required columns:
       SNP
       P

2. PLINK .clumped file

Output
------
A tab-delimited file containing:

    LD_Group
    SNP
    P

Notes
-----
The PLINK LD clumping parameters (e.g. window size and r^2)
should be specified when generating the .clumped file.

This script does not perform LD clumping itself.
It uses the LD groups generated by PLINK and performs
GWAS-based prioritization within each LD group.
"""

import argparse
import re
from pathlib import Path

import pandas as pd


# =============================================================================
# 1. Parse PLINK clumped file
# =============================================================================

def parse_clumped(clumped_file):
    """
    Parse a PLINK .clumped file and return SNP-to-LD-group assignments.

    Parameters
    ----------
    clumped_file : str or Path
        PLINK .clumped file.

    Returns
    -------
    pandas.DataFrame
        Columns:
            LD_Group
            SNP
    """

    clumped_file = Path(clumped_file)

    if not clumped_file.exists():
        raise FileNotFoundError(
            f"PLINK clumped file not found: {clumped_file}"
        )

    with open(clumped_file, "r") as f:
        lines = f.readlines()

    # -------------------------------------------------------------------------
    # Locate header line
    # -------------------------------------------------------------------------

    header_idx = None

    for i, line in enumerate(lines):
        if line.strip().upper().startswith("CHR"):
            header_idx = i
            break

    if header_idx is None:
        raise ValueError(
            f"Could not find the header line beginning with 'CHR' "
            f"in {clumped_file}"
        )

    header = lines[header_idx].strip().split()

    # -------------------------------------------------------------------------
    # Identify required columns
    # -------------------------------------------------------------------------

    try:
        snp_idx = header.index("SNP")
    except ValueError:
        raise ValueError(
            f"Column 'SNP' not found in {clumped_file}"
        )

    try:
        sp2_idx = header.index("SP2")
    except ValueError:
        raise ValueError(
            f"Column 'SP2' not found in {clumped_file}"
        )

    # -------------------------------------------------------------------------
    # Parse LD clumps
    # -------------------------------------------------------------------------

    ld_group_records = []
    ld_group_id = 0

    for line in lines[header_idx + 1:]:

        line = line.strip()

        if not line:
            continue

        parts = line.split()

        # Skip malformed rows
        if len(parts) <= max(snp_idx, sp2_idx):
            continue

        ld_group_id += 1

        lead_snp = parts[snp_idx]

        # The lead SNP always belongs to its own LD group
        group_snps = [lead_snp]

        # ---------------------------------------------------------------------
        # Parse SP2 column
        # ---------------------------------------------------------------------

        sp2 = parts[sp2_idx]

        if sp2 != "NA":

            for snp in sp2.split(","):

                # PLINK may encode SNPs as:
                # rs123(0.85)
                #
                # Remove the parenthetical LD information.
                snp_clean = re.sub(r"\([^)]*\)", "", snp)

                if snp_clean:
                    group_snps.append(snp_clean)

        # ---------------------------------------------------------------------
        # Store SNP-to-group assignments
        # ---------------------------------------------------------------------

        for snp in group_snps:

            ld_group_records.append(
                {
                    "LD_Group": ld_group_id,
                    "SNP": snp
                }
            )

    if not ld_group_records:
        raise ValueError(
            f"No LD groups were parsed from {clumped_file}"
        )

    ld_groups = pd.DataFrame(ld_group_records)

    # Remove accidental duplicate SNP assignments
    ld_groups = ld_groups.drop_duplicates(
        subset=["LD_Group", "SNP"]
    )

    return ld_groups


# =============================================================================
# 2. Read GWAS summary statistics
# =============================================================================

def read_gwas(gwas_file):
    """
    Read GWAS summary statistics.

    Required columns:
        SNP
        P
    """

    gwas_file = Path(gwas_file)

    if not gwas_file.exists():
        raise FileNotFoundError(
            f"GWAS file not found: {gwas_file}"
        )

    gwas = pd.read_csv(
        gwas_file,
        sep=r"\s+",
        engine="python"
    )

    required_columns = {"SNP", "P"}

    missing = required_columns - set(gwas.columns)

    if missing:
        raise ValueError(
            f"GWAS file is missing required columns: "
            f"{', '.join(sorted(missing))}"
        )

    # Convert P-value to numeric
    gwas["P"] = pd.to_numeric(
        gwas["P"],
        errors="coerce"
    )

    # Remove invalid P-values
    gwas = gwas.dropna(
        subset=["SNP", "P"]
    )

    # Keep only valid positive P-values
    gwas = gwas[gwas["P"] > 0]

    if gwas.empty:
        raise ValueError(
            "No valid GWAS records remain after filtering."
        )

    return gwas


# =============================================================================
# 3. Select representative SNP within each LD group
# =============================================================================

def select_lead_snps(gwas, ld_groups):
    """
    Select the SNP with the smallest GWAS P-value
    within each LD group.

    Parameters
    ----------
    gwas : pandas.DataFrame
        GWAS summary statistics.

    ld_groups : pandas.DataFrame
        SNP-to-LD-group assignments.

    Returns
    -------
    pandas.DataFrame
        Representative SNP for each LD group.
    """

    merged = pd.merge(
        ld_groups,
        gwas[["SNP", "P"]],
        on="SNP",
        how="left"
    )

    # Keep SNPs that are present in the GWAS results
    merged_valid = merged.dropna(
        subset=["P"]
    ).copy()

    if merged_valid.empty:
        raise ValueError(
            "No SNPs in the LD clumps were found in the GWAS results."
        )

    # -------------------------------------------------------------------------
    # Select SNP with minimum P-value in each LD group
    # -------------------------------------------------------------------------

    lead_idx = (
        merged_valid
        .groupby("LD_Group")["P"]
        .idxmin()
    )

    selected = (
        merged_valid
        .loc[lead_idx]
        .sort_values("LD_Group")
        .reset_index(drop=True)
    )

    return selected[
        ["LD_Group", "SNP", "P"]
    ]


# =============================================================================
# 4. Main
# =============================================================================

def main():

    parser = argparse.ArgumentParser(
        description=(
            "Select representative lead SNPs from GWAS results "
            "using PLINK LD clumping groups."
        )
    )

    parser.add_argument(
        "--gwas",
        required=True,
        help="GWAS summary statistics containing SNP and P columns."
    )

    parser.add_argument(
        "--clumped",
        required=True,
        help="PLINK .clumped file."
    )

    parser.add_argument(
        "--output",
        required=True,
        help="Output file for representative lead SNPs."
    )

    args = parser.parse_args()

    # -------------------------------------------------------------------------
    # Read inputs
    # -------------------------------------------------------------------------

    print("[1/3] Parsing PLINK LD clumping results...")

    ld_groups = parse_clumped(
        args.clumped
    )

    print(
        f"      LD groups: "
        f"{ld_groups['LD_Group'].nunique()}"
    )

    print(
        f"      SNP assignments: "
        f"{len(ld_groups)}"
    )

    print("[2/3] Reading GWAS summary statistics...")

    gwas = read_gwas(
        args.gwas
    )

    print(
        f"      GWAS SNPs: "
        f"{len(gwas)}"
    )

    # -------------------------------------------------------------------------
    # Prioritize SNPs
    # -------------------------------------------------------------------------

    print(
        "[3/3] Selecting representative SNP "
        "from each LD group..."
    )

    selected = select_lead_snps(
        gwas,
        ld_groups
    )

    # -------------------------------------------------------------------------
    # Save results
    # -------------------------------------------------------------------------

    output_file = Path(args.output)

    output_file.parent.mkdir(
        parents=True,
        exist_ok=True
    )

    selected.to_csv(
        output_file,
        sep="\t",
        index=False
    )

    print()
    print("Finished.")
    print(
        f"      Representative SNPs: "
        f"{len(selected)}"
    )
    print(
        f"      Output: {output_file}"
    )


if __name__ == "__main__":
    main()
